### ISSUE TITLE
Install pre-requisite - nlohmann-json-dev (Ubuntu/Debian)

### ISSUE THREAD

**Issue by gclair** [myriadrf/LoRa-SDR#12]
Having installed Pothos via the PPA on Ubuntu and then trying to install this project from source via Git, you should mention that the package "nlohmann-json-dev" (via Ubuntu) is a requirement or that https://github.com/nlohmann/json.git will be needed.

**Comment by yangfengxu12** [comment]
Yes. The commands is
`sudo apt-get install -y nlohmann-json-dev`

**Comment by 9600** [comment]
Updated.
