### ISSUE TITLE
The prerequisites not mentioned by Read.me.

### ISSUE THREAD

**Issue by yangfengxu12** [myriadrf/LoRa-SDR#19]
When installing LimeSDR-LoRa, there are two Prerequisites not mentioned by the author.

The first Prerequisite is to install Poco C++ library.
`sudo apt-get install libpoco-doc libpoco-dev`

And another is to install 'nlohmann-json-dev' package as shown in #12.
`sudo apt-get install -y nlohmann-json-dev`

**Comment by 9600** [comment]
Thanks, updated.
