### ISSUE TITLE
Can bladerf be used for this project

### ISSUE THREAD

**Issue by liiso7** [myriadrf/LoRa-SDR#20]
Why doesn't it work on bladerf?
![image](https://github.com/myriadrf/LoRa-SDR/assets/110809805/6739550d-6bb0-40f4-84c2-4f91d9faa18c)

**Comment by 9600** [comment]
Who knows. It was originally developed for use with LimeSDR hardware. Maybe try asking on the GNU Radio mailing list or in the BladeRF community.
