### ISSUE TITLE
Lora_simulation work only 10 times

### ISSUE THREAD

**Issue by selinux** [myriadrf/LoRa-SDR#4]
I try to run lora_simulation but it receive 10 lora packet (0 to 9) and after that all packet are dropped.

Did I miss something ? (by the way thanks for those examples)

**Comment by akoun** [comment]
Commit 99f934a5da3823d6d63f6bef51fb766bdebc7a35 is working allright
https://github.com/myriadrf/LoRa-SDR/commit/99f934a5da3823d6d63f6bef51fb766bdebc7a35

best regards
ak

**Comment by ll550** [comment]
FYI， please use the same settings as client.pth. It would be working as expected. I guess there is some typos in 4/8 hamming code.

**Comment by MINDoSOFT** [comment]
Hello everyone and happy new year !!!

I have the same issue, and tried to revert to [commit](https://github.com/myriadrf/LoRa-SDR/commit/99f934a5da3823d6d63f6bef51fb766bdebc7a35) but still nothing.

I receive packets 0 to 9 and then 
211, 213, 214, 216
...
286, 288
511, 513, 514
..
566, 568, 581
...
588

So as you can see a lot of packets are dropped.

![image](https://user-images.githubusercontent.com/890368/34516147-6cf87ea0-f07e-11e7-9a3d-3335bee62ad7.png)

My setup is Windows 8.1 and LimeSDR.

**Comment by 9600** [comment]
@guruofquality any thoughts on this?

**Comment by guruofquality** [comment]
I misunderstood the bug, the mtu for the demodulator was set very small, it exceeded the message size when the count increased. The header format stuff from the last merge took up more of the frame then it used to.

* https://github.com/myriadrf/LoRa-SDR/commit/083c966ef6f7cf3d97723a66ec89a4d35b7b86ab
